CREATE DATABASE IF NOT EXISTS photo_explorer CHARACTER SET = utf8;
SHOW DATABASES;
DROP TABLE IF EXISTS Photo;
DROP TABLE IF EXISTS Album;

CREATE TABLE Album(
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AlbumName VARCHAR(50) NOT NULL
);

CREATE TABLE Photo(
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Aperture VARCHAR(10),
	ShutterSpeed VARCHAR(10),
	Iso int(10),
	PhotoData VARCHAR(255) NOT NULL,
	AlbumID int NOT NULL, 
	
	FOREIGN KEY (AlbumID) REFERENCES Album(ID)
);


